name: Tests

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main, master, develop ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-latest]
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Display Swift Version
      run: swift --version
      
    - name: Display Xcode Version
      run: xcodebuild -version
      
    - name: Build
      run: swift build -v
      
    - name: Run Tests
      run: swift test -v --parallel
      
    - name: Test Summary
      if: always()
      run: |
        echo "## Test Results - ${{ matrix.os }}" >> $GITHUB_STEP_SUMMARY
        echo "✅ Tests completed for commit ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY

