name: Tests

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main, master, develop ]

jobs:
  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Display Swift Version
      run: swift --version
      
    - name: Display Xcode Version
      run: xcodebuild -version
      
    - name: Build
      run: swift build -v
      
    - name: Run Tests
      run: swift test -v --parallel
      
    - name: Test Summary
      if: always()
      run: |
        echo "## ✅ macOS Tests" >> $GITHUB_STEP_SUMMARY
        echo "Tests completed for commit ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
  